controller_list:
  - name: fake_arm_controller
    joints:
      - base_roll
      - shoulder_pitch
      - elbow_pitch
      - elbow_roll
      - wrist_pitch
  - name: fake_hand_controller
    joints:
      - wrist_roll